### ISSUE TITLE
User can't delete own Media file.

### ISSUE THREAD

**Issue by fastone** [thenbrent/map-cap#4]
As an Administrator user, when this plugin is enabled, I can't delete the Media file I uploaded.

When disabling this plugin, I can delete it again.

**Comment by thenbrent** [comment]
I tried to reproduce but can upload/delete media without a problem. 

MSUM doesn't actually change anything when it's deactivated. Nor does it change capabilities in each role (like "delete media") so I'm not sure it is the culprit.
