### ISSUE TITLE
can't delete Draft / Pending post type

### ISSUE THREAD

**Issue by jahshuwaa** [thenbrent/map-cap#6]
I have custom post types that do not support the "author" feature.

When using map cap (mc_map_meta_cap) users cannot delete their own (or others') custom posts if those are in Draft status. Once he Publishes it, the same user can now Delete it. It only can't be Trashed while in a Draft status.

I think there is logic in mc_map_meta_cap preventing it from being Trashed in Draft status when the custom post type doesn't support the author feature.

To test, when I add the "author" feature into my register_post_type call, edit the Draft custom post and apply an Author (or Add New custom post), the user _is able to Trash_ them when they are in Draft status.

**Comment by jahshuwaa** [comment]
I think I "fixed" this in map-cap.php

one thing was:
//$caps[0] = 'delete_' . $post_type_cap . '_posts';  // <--- "delete_myposttype_posts" isn't something that Map Cap established... "delete_myposttypes" instead...
$caps[0] = 'delete_' . $post_type_cap . 's';

also applied the same $caps[0] = 'delete_' . $post_type_cap . 's' when dealing with items in the trash but never published. Drafts in the trash.

I will fork it. Not sure if my edits are respectful of everything else going on there but maybe you would be able to tell just by looking. It did seem to solve my particular issue however.

**Comment by thenbrent** [comment]
Which version of WordPress are you using? I released this against WP3.0 and haven't checked up on it since. I know that there have been many changes made to the internal map cap functionality in WordPress since 3.1, including the 'map_meta_cap' parameter when registering a post type, so they may have broken it. It may also be an issue with how your post type is being registered.

What capabilities parameters are you setting for your custom post type? Please read the [capabilities](http://codex.wordpress.org/Function_Reference/register_post_type) section of the register post type article very carefully.

**Comment by jahshuwaa** [comment]
I am using 3.1.2. Some wp features have changed but am I correct that
delete_myposttype_posts is not a cap that Map Cap registers... it registers
delete_myposttypes.  Check the delete-related caps that are registered by
your plugin's ui form. That wouldn't be effected by wp version.

My register_post_type has capability array('location', 'locations').
Map_Meta_cap is false, the default

**Comment by thenbrent** [comment]
"delete_myposttype_posts" is a primitive capability, not a meta capability. Prior to 3.1, map meta cap was called again on delete_posts meta cap and the primitive capability could be whatever was consistently used on the map_meta_cap filter. As hinted at here in the 3.1+ codebase:

`// Prior to 3.1 we would re-call map_meta_cap here.
if ( 'delete_post' == $cap )
    $cap = $post_type->cap->$cap;
`

I had a look at the primitive capabilities introduced in 3.1 and the differences between the two map_meta_cap functions and quite frankly, the whole thing gets overly complex with the array of capabilities and locations they're test. 

I'm not willing to put in the time to test this on 3.0, 3.1 & 3.2, so if you say it definitely works on 3.1+ for deleting posts then I'll make a new release specifying 3.1+ as a requirement.

**Comment by jahshuwaa** [comment]
I'm not sure, since it was only a problem on custom post types that don't include the Author. Example:

``` php
register_post_type( 'glf_features',
        array(
            'labels' => array(
                'name' => _x('Features', 'post type general name'),
                'singular_name' => _x('Feature', 'post type singular name'),
                'add_new' => _x('Add New', 'lawn tip'),
                'add_new_item' => __('Add New Feature'),
                'edit_item' => __('Edit Feature'),
                'new_item' => __('New Feature'),
                'view_item' => __('View Feature'),
                'search_items' => __('Search Features'),
                'not_found' =>  __('No features found'),
                'not_found_in_trash' => __('No features found in Trash'),
                'parent_item_colon' => '',
                'menu_name' => 'Features'
            ),
            'public' => true,
            'has_archive' => false,
            'rewrite' => array('slug' => 'features'),
            'menu_position' => 30,
            'supports' => array(
                'title',
                'thumbnail'
            ),
            'capability_type' => array('feature', 'features')
        )
    );
```

Key line above is that 'supports' does not include 'author'. It is these posts that the limited users could not delete while in Draft status.

``` php
    register_post_type( 'glf_lawntips',
        array(
            'labels' => array(
                'name' => _x('Tips', 'post type general name'),
                'singular_name' => _x('Tip', 'post type singular name'),
                'add_new' => _x('Add New', 'tip'),
                'add_new_item' => __('Add New Tip'),
                'edit_item' => __('Edit Tip'),
                'new_item' => __('New Tip'),
                'view_item' => __('View Tip'),
                'search_items' => __('Search Tips'),
                'not_found' =>  __('No tips found'),
                'not_found_in_trash' => __('No tips found in Trash'),
                'parent_item_colon' => '',
                'menu_name' => 'Tips'
            ),
            'public' => true,
            'has_archive' => false,
            'rewrite' => array('slug' => 'tip'),
            'menu_position' => 30,
            'supports' => array(
                'title',
                'thumbnail',
                'author'
            ),
            'capability_type' => array('lawntip', 'lawntips')
        )
    );
```

Key line above is that 'supports' _does_ include 'author'. Map Cap worked fine here, as far as limited users being able to delete their own Draft post items.

Overall, I tried to trace through what is happening when Map Cap determines the author of the post. If the author data is not found...

```
if ( '' != $post->post_author ) {
```

...it is set as the current user data. According to http://codex.wordpress.org/Function_Reference/register_post_type "delete_others_posts - Controls whether objects owned by other users can be can be deleted. _If the post type does not support an author, then this will behave like delete_posts._" This doc is what prompted me to try cap "delete_features" in place of "delete_feature_posts" where there is no author data.

I will set up clean 3.0, 3.1, 3.2 installations this morning to test further. Be back soon...

**Comment by jahshuwaa** [comment]
With version 1.1 of plugin, the "can't delete draft" problem exists in all three WP 3.0, 3.1, 3.2

I am currently finding that it actually doesn't matter if the "author" feature is enabled for the CPT... you can't delete Drafts regardless, so my initial assumption about that was incorrect.

Working through testing / fixes now, including a lot of PHP errors related to checking for $_post variables that haven't been set

More to come...

**Comment by jahshuwaa** [comment]
Working in the WP 3.0 test environment, the original version 1.1 (without my recent edits) does have issues.

First of all, a boatload of errors when WP DEBUG is enabled, all related to checking $_post key values of keys that don't exist. I suppressed these by wrapping all in isset() tests, but subsequently removed because I don't want to risk introducing new errors. To make the plugin UI usable in the meantime, I turned off WP DEBUG.

I made two user accounts having role "CustomPoster" that don't have access to anything except 2 CPTs I established. (In other words, they have "read" plus whatever gets added by Map Cap)

Within Map Cap, checking and unchecking permutations of Publish, Edit Own, Edit Others, and View Private for this role will produce unexpected results. There may be others, but so far I found these cases by experimentation:
- can initiate Add New form if Edit Own is checked, but if Publish is not also checked, the Save Draft or autosave will fail
- can't edit own if Publish is not checked, even if Edit Own is checked
- can _never_ Trash own Drafts regardless of Map Cap settings, but can Trash others' drafts if Edit Others is allowed
- if own Draft is in Trash (placed there by Admin or someone with Edit Others), can _never_ permanently delete or restore own Draft regardless of settings.
- can permanently delete or restore Others Draft within Trash if Edit Others allowed, but can never delete or restore Own Draft from trash

Points to logic problems in mc_map_meta_cap

Since you released this against 3.0 and the problems are presenting in a 3.0 installation, would you want to take a look at it if I gave you access to this clean WP 3.0 test environment? I could set you up with a new admin account and credentials for the 2 limited accounts I already created.

**Comment by thenbrent** [comment]
Thanks a bunch for taking the time to do all of this testing! 

Mapping Capabilities is crazy confusing in its complexity, hence why I initially released the plugin to try and help other devs overcome the learning curve I had with it. It's clear I've missed a lot of things though!

I've got an updated version tested against 3.2 (which should also apply to 3.1). I'm using your first CPT declaration (which doesn't support author) with one major change - it sets "map_meta_cap" to true.

Once setting it to true, I see the following with each of the issues you found:
- can initiate Add New form if Edit Own is checked, but if Publish is not also checked, the Save Draft or autosave will fail

I've fixed this by assigning all the meta_caps if either publish, edit own or edit others is set. This means it's not possible to only assign "Edit Own", which makes sense because I assume if someone is allowed to edit own, they must also be allowed to create their own posts. 
- can't edit own if Publish is not checked, even if Edit Own is checked

This should also be fixed with the above change. 
- can never Trash own Drafts regardless of Map Cap settings, but can Trash others' drafts if Edit Others is allowed

Try this again now. It should also be fixed. 
- if own Draft is in Trash (placed there by Admin or someone with Edit Others), can never permanently delete or restore own Draft regardless of settings.

Again, should be fixed.
- can permanently delete or restore Others Draft within Trash if Edit Others allowed, but can never delete or restore Own Draft from trash

Also should be fixed. 

You can look at the commit log, but in summary, the major changes I made were: 
- completely removing the `mc_map_meta_cap()` - this code is now implemented by WP itself (as of 3.1+). I'd prefer to work with WP so I'm going to set the plugin to require 3.1 and use the internal code
- adding all meta caps to a role if any of publish, edit own, edit others is set, this is more correct than the previous version
- change the capability assignments from `'action_status_' . $post_type_cap . 'posts'` to `'action_status_' . $post_type_cap . 's'` eg. `'delete_published_' . $post_type_cap . 'posts'` is now `'delete_published_' . $post_type_cap . 's'`
- added in the `'delete_others_' . $post_type_cap . 's'` capability

Most of these changes are available in commit SHA: a6bb47da0f7a0596441e1f53c70d7c2415f90cd6

Please pull or download the dev version from github and let me know how you go. 

If it's all working correctly I'll make a public release.

I'd also like to include your name as a plugin author to thank you for your help, if you have a WordPress.org account and would like to have your name added to it.

**Comment by thenbrent** [comment]
Again, just to highlight that I'm setting `map_meta_cap` to `true`, here is the RPT call I was testing against:

``` php
<?php
    register_post_type( 'glf_features',
            array(
                'labels'                 => array(
                    'name'               => _x('Features', 'post type general name'),
                    'singular_name'      => _x('Feature', 'post type singular name'),
                    'add_new'            => _x('Add New', 'lawn tip'),
                    'add_new_item'       => __('Add New Feature'),
                    'edit_item'          => __('Edit Feature'),
                    'new_item'           => __('New Feature'),
                    'view_item'          => __('View Feature'),
                    'search_items'       => __('Search Features'),
                    'not_found'          =>  __('No features found'),
                    'not_found_in_trash' => __('No features found in Trash'),
                    'parent_item_colon'  => '',
                    'menu_name'          => 'Features'
                ),
                'public'                 => true,
                'has_archive'            => false,
                'rewrite'                => array('slug' => 'features'),
                'menu_position'          => 30,
                'supports'               => array(
                    'title',
                    'thumbnail'
                ),
                'capability_type'        => array('feature', 'features'),
                'map_meta_cap'           => true
            )
        );
```

**Comment by jahshuwaa** [comment]
Clearly making it 3.1 minimum was the new way to go.   :-)   I will test this afternoon and give you the results.

My wordpress.org account is
jahshuwaa

Thanks!

Would you consider the following flag / isset logic instead of the @ error buffering?
(Note this is from the previous version)

``` php
// Shared capability required to see post's menu
            $set_edit_posts = false;
            if ( isset( $_POST[ $post_type . '-' . $key . '-publish' ] ) )
                if ( 'on' == $_POST[ $post_type . '-' . $key . '-publish' ] ) $set_edit_posts = true;
            if ( isset( $_POST[ $post_type . '-' . $key . '-edit' ] ) )
                if ( 'on' == $_POST[ $post_type . '-' . $key . '-edit' ] )  $set_edit_posts = true;
            if ( isset( $_POST[ $post_type . '-' . $key . '-edit-others' ] ) )
                if ( 'on' == $_POST[ $post_type . '-' . $key . '-edit-others' ] )  $set_edit_posts = true;

            if ( $set_edit_posts )
                $role->add_cap( $post_type_caps->edit_posts );
            else
                $role->remove_cap( $post_type_caps->edit_posts );


            // Allow publish
            $set_publish_posts = false;
            if ( isset( $_POST[ $post_type . '-' . $key . '-publish' ] ) )
                if ( 'on' == $_POST[ $post_type . '-' . $key . '-publish' ] ) $set_publish_posts = true;

            if ( $set_publish_posts ) {
                $role->add_cap( $post_type_caps->publish_posts );
                $role->add_cap( $post_type_caps->delete_post . 's');
            } else {
                $role->remove_cap( $post_type_caps->publish_posts );
                $role->remove_cap( $post_type_caps->delete_post . 's');
            }


            // Allow editing own posts
            $set_edit_own_posts = false;
            if ( isset( $_POST[ $post_type . '-' . $key . '-edit' ] ) )
                if ( 'on' == $_POST[ $post_type . '-' . $key . '-edit' ] ) $set_edit_own_posts = true;
            if ( isset( $_POST[ $post_type . '-' . $key . '-edit-others' ] ) )
                if ( 'on' == $_POST[ $post_type . '-' . $key . '-edit-others' ] )  $set_edit_own_posts = true;

            if ( $set_edit_own_posts ) {
                $role->add_cap( 'edit_published_' . $post_type_cap . '_posts' );
                $role->add_cap( 'delete_published_' . $post_type_cap . '_posts' );
                $role->add_cap( 'edit_private_' . $post_type_cap . '_posts' );
            } else {
                $role->remove_cap( 'edit_published_' . $post_type_cap . '_posts' );
                $role->remove_cap( 'delete_published_' . $post_type_cap . '_posts' );
                $role->remove_cap( 'edit_private_' . $post_type_cap . '_posts' );
            }


            // Allow editing other's posts
            $set_edit_others_posts = false;
            if ( isset( $_POST[ $post_type . '-' . $key . '-edit-others' ] ) )
                if ( 'on' == $_POST[ $post_type . '-' . $key . '-edit-others' ] ) $set_edit_others_posts = true;

            if ( $set_edit_others_posts )
                $role->add_cap( $post_type_caps->edit_others_posts );
            else
                $role->remove_cap( $post_type_caps->edit_others_posts );


            // Allow reading private
            $set_read_private = false;
            if ( isset( $_POST[ $post_type . '-' . $key . '-private' ] ) )
                if ( 'on' == $_POST[ $post_type . '-' . $key . '-private' ] ) $set_read_private = true;

            if ( $set_read_private )
                $role->add_cap( $post_type_caps->read_private_posts);
            else
                $role->remove_cap( $post_type_caps->read_private_posts );
```

**Comment by thenbrent** [comment]
Using isset is a better solution than just buffering the errors so if it's
all working for you, I'll go through and do the proper checking prior to
release.

**Comment by jahshuwaa** [comment]
OK. One necessary checkbox combination won't save:
Publish: NO
Edit Own: YES
Edit Others: (Either)
View Private (Either)

Publish NO + Edit Own YES should probably be allowed -- e.g. a contributor-type person who is allowed to create the post,save draft and submit for approval, but not publish autonomously

Other than that it's working great now in the test case

One last thought to drive you crazy. Is the new code going to be OK with a capability_type array like this:
        'capability_type'        => array('story', 'stories')

... where plural form is not singular with appended 's'

string builds like 'delete_published_' . $post_type_cap . 's' -- do they assume singular plus 's' on the capability_type ?

**Comment by thenbrent** [comment]
Hrm, I'll have to take a look at how to allow publishing but not editing.
That will mean a user can not permanently delete their own draft that is in
the trash though I'm pretty sure (as the status is no longer trash).

You're right, the brute force "s" appending will break any post type with
cap != +'s'. I tried looking in the caps array (eg. publish_story,
publish_stories) but it didn't contain all of the need primitive
capabilities so they must be built manually. I'll see if I can find a place
where the plural base capability is available though and use that - it
should be in there somewhere.

**Comment by jahshuwaa** [comment]
I did see them in caps in 3.1... unless there are other props needed?

**register_post_type with:**

``` php
'capability_type' => array('noauthorstory', 'noauthorstories'),
'map_meta_cap' => true
```

**I added a print_r to the settings page just to check:**

``` php
<div class="map-cap">
<h4><?php printf( __( "Publish %s", 'map-cap' ), $post_type_details->labels->name );
print_r($post_type_details->cap); ?></h4>
```

**Output:**

Publish Authorless Post
stdClass Object (
[edit_post] => edit_noauthorstory
[read_post] => read_noauthorstory
[delete_post] => delete_noauthorstory
[edit_posts] => edit_noauthorstories
[edit_others_posts] => edit_others_noauthorstories
[publish_posts] => publish_noauthorstories
[read_private_posts] => read_private_noauthorstories
[read] => read
[delete_posts] => delete_noauthorstories
[delete_private_posts] => delete_private_noauthorstories
[delete_published_posts] => delete_published_noauthorstories
[delete_others_posts] => delete_others_noauthorstories
[edit_private_posts] => edit_private_noauthorstories
[edit_published_posts] => edit_published_noauthorstories
)

**Comment by thenbrent** [comment]
I'm either going blind or crazy - I just checked the caps again and they are
all there, so I've switched to using the object item instead of the nasty
manual addition of 's' for plural.

I've also updated the logic so a role can now have Publish NO + Edit Own
YES.

Finally I've updated the error handling to check items are set rather than
buffering.

Let me know if it's all working!

**Comment by jahshuwaa** [comment]
Very close I think. Only thing I still have trouble with is unable to delete own draft, unless Publish is granted.

I think it comes down to the "// Allow publish" section in mc_save_capabilities; publish_posts is bound to delete_posts (thus what behavior I'm seeing -- if I don't give publish, I don't get delete)

I did an experiment with the "User Role Editor" plugin. I gave my custom role "edit_posts" and "delete_posts". Doing this for **non**-custom posts results in the behavior I wanted --- user with role can create / edit / trash / restore / delete permanently. But cannot publish; they only get the Save Draft and Submit for Review buttons.

**Speaking about regular old posts only, User Role Editor had relevant checkboxes for 10 capabilities:**

read_private_posts

edit_posts
edit_others_posts
edit_private_posts
edit_published_posts

publish_posts

delete_posts
delete_others_posts
delete_private_posts
delete_published_posts

If you had these 10 checkboxes on the Map Cap form for each Custom Type, everything would be separate (e.g. no Publish & Delete binding). Then just do the logic checks on saving... grant "edit_posts" if any of the other 3 "edit_" are checked. Same for "delete_"

Is there a problem you can think of, doing the Map Cap setting form this way?

**Comment by thenbrent** [comment]
I was avoiding breaking the UI down to individual capabilities to try to keep things simple. 

It was "task" focused rather than "capabilitity focused". I also didn't think there was a use case for deleting posts if you couldn't also publish (but I didn't account for the "pending review" status). 

I've refactored the delete cap to be set if a user can either edit or publish (or combination of both). That will solve the problem for you. 

Think it's ready for release?

**Comment by jahshuwaa** [comment]
It's working now.

I'll use another capability manager in combination with Map Cap to remove delete_published_posts. Only administrators should be able to do this on my site -- 404s the indexed permalink.

Thanks for bearing with me & providing all these updates!

**Comment by thenbrent** [comment]
Great, I'll make a public release. I'm happy to help anyone who is patient, polite and willing to work with me, as you have been. Best of luck. :)
