### ISSUE TITLE
Styling

### ISSUE THREAD

**Issue by lloc** [thenbrent/map-cap#9]
Do you have plans to style the output in the backend? The presentation is a little bit confusing if there are a lot of Custom Post Types.

Of course I could also help here if you like.

Cheers,
Dennis.

**Comment by thenbrent** [comment]
I don't have plans to, but if you're willing to style it up, I'd be very happy to merge it and put your name in the "Author" meta so you show as an author on wp.org. :)

**Comment by lloc** [comment]
https://github.com/thenbrent/map-cap/pull/10
